before_script:
  # Setup SSH deploy keys
  - 'which ssh-agent || (sudo apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - test
  - deploy

test:
  image : mcr.microsoft.com/dotnet/sdk:6.0
  stage: test
  script:
    - dotnet test

deploy:
  stage: deploy
  script:
    - ssh $SERVER_ADDRESS "cd if3250_2022_35_cakrawala_backend; sudo docker-compose down; git pull --rebase origin main; sudo docker-compose up --build -d; exit;"
  only:
    - main