before_script:
  - rm -rf ~/.ssh
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' >  ~/.ssh/azurevmkey.pem
  - chmod 400 ~/.ssh/azurevmkey.pem

stages:
  - test
  - deploy

test:
  image : mcr.microsoft.com/dotnet/sdk:6.0
  stage: test
  script:
    - dotnet test

deploy:
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no -i ~/.ssh/azurevmkey.pem $SERVER_ADDRESS "cd if3250_2022_35_cakrawala_backend; sudo docker-compose down; git pull --rebase origin main; sudo docker-compose up --build -d; exit;"
  only:
    - main