version: '3.4'

services:
    postgresqldb:
        image: postgres:latest
        env_file:
            - '.env'
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - database-data:/var/lib/postgresql/data/
        networks:
            - app-network       
    
    pgadmin:
        image: dpage/pgadmin4
        env_file:
            - '.env'
        ports:
            - "5050:80"
        restart: always
        volumes: 
            - pgadmin:/root/.pgadmin
        networks:
            - app-network

    server:
        build:
            context: ./
        env_file:
            - '.env'
        ports:
            - "5000:80"
        restart: unless-stopped
        links:
            - postgresqldb
        networks:
            - app-network

    nginx:
        restart: unless-stopped
        image: nginx
        ports:
           - "80:80"
           - "443:443"
        volumes:
           - ./nginx/nginx.conf:/etc/nginx/nginx.conf
           - ./certbot/conf:/etc/letsencrypt
           - ./certbot/www:/var/www/certbot
        networks:
           - app-network

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
          - ./certbot/conf:/etc/letsencrypt
          - ./certbot/www:/var/www/certbot
        command: certonly --webroot -w /var/www/certbot --force-renewal --email kadeksuryam087@gmail.com -d cakrawala-id.southeastasia.cloudapp.azure.com --agree-tos

volumes:
    database-data:
    pgadmin:

networks:
  app-network:
    driver: bridge
